---
enterprise_tags:

  Application: "{{ tag_application | default('') }}"

  Environment: "{{ tag_environment | default('') }}"

  BusinessUnit: "{{ tag_business_unit | default('') }}"

  CostCenter: "{{ tag_cost_center | default('') }}"

  Owner: "{{ tag_owner | default('') }}"

  ManagedBy: "{{ tag_managed_by | default('Ansible') }}"

  DataClassification: "{{ tag_data_classification | default('') }}"